---
title: "What Drives Article Popularity?"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(ggplot2)
library(dplyr)
library(gbm)
library(tidyverse)
library(corrplot)
library(party)
library(reshape2)
library(caTools)
 library(xgboost) 
set.seed(1234)

news_data <- read.csv('Data/dat_train.csv')
news_data$popular<-ifelse(news_data$shares<1400,"no","yes")
```

## What Are The Patterns in Our Data?

```{r}
#plot(news_data$kw_avg_avg,news_data$shares,xlim=c(1,10000),ylim=c(1,20000))
#abline(lm(news_data$shares~news_data$kw_avg_avg))

ggplot(news_data, aes(as.factor(is_weekend)))+
geom_bar(aes(fill = popular))+
labs(x = "Article posted at the weekend",y = "Number of articles based on popularity")

ggplot(news_data, aes(as.factor(data_channel_is_socmed)))+
geom_bar(aes(fill = popular))+
labs(x = "Social media channel",y = "Number of articles based on popularity")

#ggplot(news_data, aes(x=factor(is_weekend), y=shares)) + stat_summary(fun.y="mean", geom="bar")
#ggplot(news_data, aes(x=factor(data_channel_is_socmed ), y=shares)) + stat_summary(fun.y="mean", geom="bar")
#ggplot(news_data, aes(x=factor(data_channel_is_tech), y=shares)) + stat_summary(fun.y="mean", geom="bar")


ggplot(news_data, aes(x = news_data$kw_avg_avg)) +
  geom_histogram(aes(color = popular, fill = popular), 
                position = "identity", bins = 500, alpha = 0.4) +
  coord_cartesian(xlim = c(0, 7500), ylim = c(0, 750))+
labs(x = "Avg. keyword (avg. shares)")


num<-unlist(lapply(news_data, is.numeric))
news_data_cor<-news_data[,num]
cor.matrix<-cor(news_data_cor)
corrplot(cor.matrix, order="hclust", tl.pos='n') 

```




```{r , cache= TRUE,include=FALSE}
## 4.Test/Train Dataset
## 80% of the sample size
smp_size <- floor(0.80 * nrow(news_data))
train_ind <- sample(seq_len(nrow(news_data)), size = smp_size)
news_train <- news_data[train_ind, ]
news_test <- news_data[-train_ind, ]
```

## Predictive Model 

```{r,cache=TRUE,include=FALSE}
myControl <- trainControl(
  method = "cv",
  number = 5,
  verboseIter = FALSE
)
model_gbm <- train(popular ~., data = news_train[,!names(news_train) %in% c("url","timedelta","shares")], method = "gbm",
                   trControl = myControl,preProcess = c("corr"))
```

```{r}
model_gbm
#summary(model_gbm)

plot(varImp(model_gbm),5)


gbm.pred1<-predict(model_gbm,newdata=news_test[,!names(news_test) %in% c("url","timedelta","shares")])
ctable <- as.table(confusionMatrix(gbm.pred1,as.factor(news_test$popular)), nrow = 2, byrow = TRUE)
fourfoldplot(ctable, color = c("#CC6666", "#99CC99"),
             conf.level = 0, margin = 1, main = "Confusion Matrix")
```

## Best Practice Approach For Writing Articles


* publish during weekends
* publish on at least one social media channel
* keywords are important, use the words that were in popular articles before
  




